name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: ${{ vars.JWT_SECRET }}
      EXPIRES_IN_TOKEN: ${{ vars.EXPIRES_IN_TOKEN }}
      PORT: ${{ vars.PORT }}
      NODE_ENV: ${{ vars.NODE_ENV }}
      JWT_SECRET_REFRESH: ${{ vars.JWT_SECRET_REFRESH }}
      ACCESS_TOKEN_EXPIRES: ${{ vars.ACCESS_TOKEN_EXPIRES }}
      REFRESH_TOKEN_EXPIRES: ${{ vars.REFRESH_TOKEN_EXPIRES }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: |
          cd back
          npm install

      - name: Run tests
        run: |
          cd back
          npm test
